const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ Yamar" 


global.devs = "237672114754" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "237672114754";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "237672114754";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_10_43_07_26_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODAsXG4gICAgICAgIDcxLFxuICAgICAgICA4MyxcbiAgICAgICAgMTU5LFxuICAgICAgICA3LFxuICAgICAgICAxOTcsXG4gICAgICAgIDcyLFxuICAgICAgICAyNTAsXG4gICAgICAgIDYyLFxuICAgICAgICAyMDcsXG4gICAgICAgIDExNSxcbiAgICAgICAgMjMwLFxuICAgICAgICAxNjEsXG4gICAgICAgIDc1LFxuICAgICAgICAzNCxcbiAgICAgICAgMTk2LFxuICAgICAgICAxMTQsXG4gICAgICAgIDE3NixcbiAgICAgICAgMjA5LFxuICAgICAgICAxMzgsXG4gICAgICAgIDM4LFxuICAgICAgICA3OSxcbiAgICAgICAgMTU4LFxuICAgICAgICAyMDIsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTExLFxuICAgICAgICAxMDYsXG4gICAgICAgIDI5LFxuICAgICAgICAxMzUsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMjQwLFxuICAgICAgICAxMjRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTc0LFxuICAgICAgICA4LFxuICAgICAgICAyMzIsXG4gICAgICAgIDExNixcbiAgICAgICAgMTI5LFxuICAgICAgICAyNTUsXG4gICAgICAgIDEyLFxuICAgICAgICAxMjAsXG4gICAgICAgIDE4OSxcbiAgICAgICAgMTA2LFxuICAgICAgICA2OSxcbiAgICAgICAgODAsXG4gICAgICAgIDI0LFxuICAgICAgICAyMjIsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTk5LFxuICAgICAgICAyMjcsXG4gICAgICAgIDcwLFxuICAgICAgICAyMTgsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTgxLFxuICAgICAgICAxNzksXG4gICAgICAgIDk5LFxuICAgICAgICAzMCxcbiAgICAgICAgNDAsXG4gICAgICAgIDQ5LFxuICAgICAgICAxNzYsXG4gICAgICAgIDczLFxuICAgICAgICAyMjIsXG4gICAgICAgIDEyLFxuICAgICAgICAxODAsXG4gICAgICAgIDNcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQ4LFxuICAgICAgICAxNzEsXG4gICAgICAgIDIyNyxcbiAgICAgICAgNTMsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMTksXG4gICAgICAgIDEzMyxcbiAgICAgICAgNDQsXG4gICAgICAgIDI0NyxcbiAgICAgICAgNjEsXG4gICAgICAgIDE2MSxcbiAgICAgICAgMjgsXG4gICAgICAgIDE5NCxcbiAgICAgICAgNjIsXG4gICAgICAgIDQsXG4gICAgICAgIDIxOCxcbiAgICAgICAgOTEsXG4gICAgICAgIDUsXG4gICAgICAgIDk0LFxuICAgICAgICAxNzYsXG4gICAgICAgIDk0LFxuICAgICAgICA1OSxcbiAgICAgICAgMTI1LFxuICAgICAgICA5NSxcbiAgICAgICAgMTI1LFxuICAgICAgICAyOCxcbiAgICAgICAgMTQ4LFxuICAgICAgICAyMzMsXG4gICAgICAgIDc2LFxuICAgICAgICA1NCxcbiAgICAgICAgMjI3LFxuICAgICAgICA4M1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjQsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMzYsXG4gICAgICAgIDYsXG4gICAgICAgIDE5MCxcbiAgICAgICAgODQsXG4gICAgICAgIDYwLFxuICAgICAgICA1NixcbiAgICAgICAgMTMwLFxuICAgICAgICAxNTEsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjQwLFxuICAgICAgICA5MixcbiAgICAgICAgMTQ3LFxuICAgICAgICAxOTcsXG4gICAgICAgIDE5NCxcbiAgICAgICAgNjIsXG4gICAgICAgIDcxLFxuICAgICAgICAxMixcbiAgICAgICAgNDMsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjI5LFxuICAgICAgICAxMzUsXG4gICAgICAgIDExMSxcbiAgICAgICAgNzUsXG4gICAgICAgIDc2LFxuICAgICAgICAzLFxuICAgICAgICAyMTEsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTY4LFxuICAgICAgICAyMjcsXG4gICAgICAgIDY5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjAsXG4gICAgICAgIDMzLFxuICAgICAgICAzNyxcbiAgICAgICAgMTEwLFxuICAgICAgICAyMDgsXG4gICAgICAgIDEyMSxcbiAgICAgICAgNjAsXG4gICAgICAgIDQ1LFxuICAgICAgICAxNjMsXG4gICAgICAgIDU1LFxuICAgICAgICA2MSxcbiAgICAgICAgMjAxLFxuICAgICAgICAxMTksXG4gICAgICAgIDE4MixcbiAgICAgICAgNTIsXG4gICAgICAgIDgwLFxuICAgICAgICAzNixcbiAgICAgICAgMTgsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTc5LFxuICAgICAgICA2NSxcbiAgICAgICAgMTg5LFxuICAgICAgICAxMzgsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTIwLFxuICAgICAgICAxNDIsXG4gICAgICAgIDE2NixcbiAgICAgICAgNjEsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMjQ5LFxuICAgICAgICAxMDQsXG4gICAgICAgIDEwMFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNSxcbiAgICAgICAgMzgsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjA2LFxuICAgICAgICA3MyxcbiAgICAgICAgMTAyLFxuICAgICAgICAxNDAsXG4gICAgICAgIDc4LFxuICAgICAgICA3MCxcbiAgICAgICAgNDcsXG4gICAgICAgIDIwMixcbiAgICAgICAgNjgsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMjUxLFxuICAgICAgICA2OSxcbiAgICAgICAgMjI1LFxuICAgICAgICA4LFxuICAgICAgICA0NSxcbiAgICAgICAgMTk0LFxuICAgICAgICAyNTUsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTk1LFxuICAgICAgICA2MCxcbiAgICAgICAgMjU1LFxuICAgICAgICAyLFxuICAgICAgICA2OCxcbiAgICAgICAgMTEwLFxuICAgICAgICAxNzgsXG4gICAgICAgIDkzLFxuICAgICAgICA1MCxcbiAgICAgICAgMjQyLFxuICAgICAgICAyOFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNTIsXG4gICAgICAgICAgODIsXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDEyOSxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMjIzLFxuICAgICAgICAgIDIzNyxcbiAgICAgICAgICAzMixcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgODMsXG4gICAgICAgICAgMjQzLFxuICAgICAgICAgIDI1MSxcbiAgICAgICAgICAxMyxcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDc1LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAyOSxcbiAgICAgICAgICA3N1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMzAsXG4gICAgICAgICAgMjIwLFxuICAgICAgICAgIDI0NSxcbiAgICAgICAgICAxMzIsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDIzNSxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDE2OSxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgMjA5LFxuICAgICAgICAgIDIwMixcbiAgICAgICAgICAxNjMsXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAxNzksXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgMjM2LFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICA0MCxcbiAgICAgICAgICA0OCxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMjUxLFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgMTE2LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICAxNVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDM1LFxuICAgICAgICAxNDQsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMTk5LFxuICAgICAgICAyMjUsXG4gICAgICAgIDE1OCxcbiAgICAgICAgMTA3LFxuICAgICAgICAyLFxuICAgICAgICAyMDgsXG4gICAgICAgIDc0LFxuICAgICAgICAyOCxcbiAgICAgICAgNTMsXG4gICAgICAgIDY5LFxuICAgICAgICA0OCxcbiAgICAgICAgMjI5LFxuICAgICAgICAxNzcsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTM3LFxuICAgICAgICAyMzQsXG4gICAgICAgIDE3MyxcbiAgICAgICAgNDAsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMzcsXG4gICAgICAgIDIyNSxcbiAgICAgICAgMTM2LFxuICAgICAgICAxNTAsXG4gICAgICAgIDE0LFxuICAgICAgICAyNDIsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTI4LFxuICAgICAgICAyMTYsXG4gICAgICAgIDIwMixcbiAgICAgICAgMjQ0LFxuICAgICAgICA4LFxuICAgICAgICAyOCxcbiAgICAgICAgMTI0LFxuICAgICAgICAxNTksXG4gICAgICAgIDM1LFxuICAgICAgICA1MSxcbiAgICAgICAgMjMzLFxuICAgICAgICA0OCxcbiAgICAgICAgODYsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMjI0LFxuICAgICAgICA4NixcbiAgICAgICAgMjQxLFxuICAgICAgICAyLFxuICAgICAgICAxNzAsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTMyLFxuICAgICAgICAxNzMsXG4gICAgICAgIDQ5LFxuICAgICAgICA5MyxcbiAgICAgICAgMTU0LFxuICAgICAgICAxNjIsXG4gICAgICAgIDEyNixcbiAgICAgICAgMjIsXG4gICAgICAgIDcsXG4gICAgICAgIDIzLFxuICAgICAgICAzMixcbiAgICAgICAgOTEsXG4gICAgICAgIDExMyxcbiAgICAgICAgODgsXG4gICAgICAgIDNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDEyMixcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJWOFloUE42ZlFDMUhUcmoycStmamY5TUhpd0E4bHhKSnRHMjNLbzcyZzJ3PVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCItVjNFTllWNVNjcTJCaVhZVVZQb2JRXCIsXG4gIFwicGhvbmVJZFwiOiBcIjE2NGNmYmM4LWQ0MzMtNDMzMS05MTUxLWY0ZjQ4NTA0YmVlYlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA4OSxcbiAgICAgIDE2NSxcbiAgICAgIDE4NyxcbiAgICAgIDE0MSxcbiAgICAgIDE4MyxcbiAgICAgIDIzOSxcbiAgICAgIDI4LFxuICAgICAgMTU2LFxuICAgICAgMjEwLFxuICAgICAgMjM3LFxuICAgICAgNzUsXG4gICAgICAxMDEsXG4gICAgICAxMDEsXG4gICAgICAxMDksXG4gICAgICAxODIsXG4gICAgICAxOTcsXG4gICAgICAxNjQsXG4gICAgICAxMTcsXG4gICAgICAyNTUsXG4gICAgICAxMTJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE0MixcbiAgICAgIDE1NyxcbiAgICAgIDE2NyxcbiAgICAgIDE3MyxcbiAgICAgIDIyMSxcbiAgICAgIDksXG4gICAgICA3NixcbiAgICAgIDEyNyxcbiAgICAgIDY5LFxuICAgICAgOCxcbiAgICAgIDIwNSxcbiAgICAgIDE4MixcbiAgICAgIDEzLFxuICAgICAgMSxcbiAgICAgIDU2LFxuICAgICAgMTk5LFxuICAgICAgMTc0LFxuICAgICAgMTY1LFxuICAgICAgMTM5LFxuICAgICAgNjdcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNJdmVrVHdRd3Z1TnRRWVlBU0FBS0FBPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcImFBeTEzdFB2NDJ1ZXREazdHVk9qc2Z4K1dlblU3MEo4NU5iQ1ZMakNjbHM9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiRHd3RTZjU09mdlU5NXJIeis1dGFGZk40djljWDBrYzhvSFRBZlR3OVZMS1Y2R01NMGZQQStScXQ2NmJJMHpVd0NBVlFqSlY4U0MvN3Z3aWtPdElhQUE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwibEdycmdzK2taME00enpVWDB6RzdrallZb1dVenFId3JkREFNNUlCMXQxTFNPdzRsTExtWXFFeDBESnZJMzlYWHN2emZkZVA4YlR1bHBlTVZBV25PQnc9PVwiXG4gIH0sXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzc2NzIxMTQ3NTQ6MThAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjc0NDcwOTU4MDU5NjYxOjE4QGxpZFwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM3NjcyMTE0NzU0OjE4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgMjExLFxuICAgICAgICAgIDIzOSxcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgMTYzLFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgMTI2LFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDIzMyxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgMjE0LFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgMTk0LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICA5MVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIxOTkwNTk4LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBRWUrXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFFZSsuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJWSk1QQThtOGE5R2IxS2JDaVpTVk1sT0FRNkdlRGlYUE10azRHSlN4ZjgwPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEyNjExOTY5MCxcImN1cnJlbnRJbmRleFwiOjQsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyMTk5MDExNjkxM1wifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUVlMi5qc29uIjogIntcImtleURhdGFcIjpcIk1hYzRGRExqbUdFQUs5b01iMFBLRVJiVjRueGw5RWZBeFZOVnRUWkt3Qjg9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTI2MTE5Njg2LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzIwNTE1MDA4ODQ4XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRWUzLmpzb24iOiAie1wia2V5RGF0YVwiOlwiRXBLRkJpSXBpcis5NklDOW1PQ0xKeUFpTVd2YTAzYnBtb2FZWUVxTXZqcz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjYxMTk2ODcsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyMDUxNTM0OTY1OFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUVlNC5qc29uIjogIntcImtleURhdGFcIjpcIkd3d0lEVHZVU0h1TkJBTWExOSsxUk9ZWmdlcmQ4TUFiNU9GWTloVEJJYTQ9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTI2MTE5Njg4LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzIwNTE4MzUxMDM2XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRWU1Lmpzb24iOiAie1wia2V5RGF0YVwiOlwiZVZlNjJiMXhVQWZsZ1JURk9tZDJUbEMvUlN4dmpWV2FQRGF1TUNheGhiWT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjYxMTk2ODksXCJjdXJyZW50SW5kZXhcIjoyLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUVlNi5qc29uIjogIntcImtleURhdGFcIjpcImIyeFFtWmt0ZE1JbVJvd21ML2VzbDI3U3U2UmNQRXhYVXdmTElUMFZDWGs9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTI2MTE5NjkwLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjA1NDM4NjIyNTdcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFFZTcuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJxdmxHWlNyWGp6eWNualJPV1RaVHhFaVpjWlZJQS9IdkVvOGdsdTNncUlJPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEyNjExOTY5MCxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzIxMDgzMzU0MjgyXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRWU4Lmpzb24iOiAie1wia2V5RGF0YVwiOlwiOGtMWHFXN2YrR3czd3NOOUVESVFhNGM2RTZoOTIvRys2TGxGaldpa0lwQT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjYxMTk2OTAsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDEsNF19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRWU5Lmpzb24iOiAie1wia2V5RGF0YVwiOlwiUGtYL0I1SlJER0FNUEltZ1pFU0dmaWhjTWt4WFl6V0k4YWQ0VXlNZ0tWVT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjYxMTk2OTAsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDRdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
